/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TurnsIndexRouteImport } from './routes/turns/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as TurnsCreateRouteImport } from './routes/turns/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnsIndexRoute = TurnsIndexRouteImport.update({
  id: '/turns/',
  path: '/turns/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnsCreateRoute = TurnsCreateRouteImport.update({
  id: '/turns/create',
  path: '/turns/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/turns/create': typeof TurnsCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/turns': typeof TurnsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/turns/create': typeof TurnsCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/turns': typeof TurnsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/turns/create': typeof TurnsCreateRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/turns/': typeof TurnsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/turns/create' | '/users/$userId' | '/turns' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/turns/create' | '/users/$userId' | '/turns' | '/users'
  id:
    | '__root__'
    | '/'
    | '/turns/create'
    | '/users/$userId'
    | '/turns/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TurnsCreateRoute: typeof TurnsCreateRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  TurnsIndexRoute: typeof TurnsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turns/': {
      id: '/turns/'
      path: '/turns'
      fullPath: '/turns'
      preLoaderRoute: typeof TurnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turns/create': {
      id: '/turns/create'
      path: '/turns/create'
      fullPath: '/turns/create'
      preLoaderRoute: typeof TurnsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TurnsCreateRoute: TurnsCreateRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  TurnsIndexRoute: TurnsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
